/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Mixko
 */
public class pointPanel extends javax.swing.JPanel {

    /**
     * Creates new form pointPanel
     */
    int N = 10;
    int[][] point = new int[N][2];
    int[] closestPoint1 = new int[2];
    int[] closestPoint2 = new int[2];
    
    int[][] convexHull = new int[N][4];
    
    public pointPanel(int[][] p, int[] p1, int[] p2) {
        this.point = p;
        closestPoint1 = p1;
        closestPoint2 = p2;
        initComponents();
    }
    
    public void paintComponent(Graphics page){
        for (int i = 0; i < point.length; i++) {
            page.drawOval(point[i][0], point[i][1], 10, 10);
        }
        page.setColor(Color.PINK);
        page.drawLine(closestPoint1[0]+5, closestPoint1[1]+5, closestPoint2[0]+5, closestPoint2[1]+5);
        page.setColor(Color.red);
        for (int i = 0; i < convexHull.length; i++) {
            page.drawLine(convexHull[i][0]+5, convexHull[i][1]+5, convexHull[i][2]+5, convexHull[i][3]+5);
        }
    }
    
    public void getConvex(int [][] c){
        convexHull = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
